name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "master"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "node-heroku"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          VERSION: GitHub Actions Shell
       
          # HEROKU_API_KEY and HEROKU_EMAIL will need to be set in repository secrets
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Ubuntu
        run: env